# Generated by Django 2.2 on 2022-01-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('goodsname', models.CharField(max_length=64)),
                ('goodsstatus', models.IntegerField()),
                ('checkstate', models.IntegerField()),
                ('pic', models.CharField(max_length=128)),
                ('issuetime', models.DateField()),
                ('goodscate', models.ForeignKey(null=True, on_delete='CASCADE', to='app01.Category')),
                ('issueperson', models.ForeignKey(on_delete='CASCADE', to='app01.User', to_field='userid')),
            ],
        ),
    ]
